### ISSUE TITLE
Is this now integrated into click as click.testing?

### ISSUE THREAD

**Issue by eli-b** [Stranger6667/pytest-click#2]
If so, it would be helpful to note in the docs that the PyPI plugin is no longer needed.

**Comment by Stranger6667** [comment]
Hi @eli-b !

Unfortunately, I can't find a py.test fixture in `click` repo, could you, please point me to it?

Thanks

**Comment by eli-b** [comment]
I should have linked to: http://click.pocoo.org/6/testing/.

https://github.com/pallets/click/blob/master/tests/conftest.py uses CliRunner as a fixture, for example.

**Comment by Stranger6667** [comment]
`tests` directory is not included in the `click` distribution, so, the users can't access the fixtures from `tests/conftest.py` when they install `click` in their environment.
The plugin provides an (a very small) addition to `click`, wrapping CLI runner from `click.testing` into py.test fixtures and provides some configuration options.

Thus being said, the answer to your question is - No, this library is not integrated to `click`.

**Comment by eli-b** [comment]
Now I see what this plugin adds to Click. Thanks!

בתאריך יום ד׳, 1 באוג׳ 2018, 01:05, מאת Dmitry Dygalo ‏<
notifications@github.com>:

**Comment by Stranger6667** [comment]
You are welcome! :)
